import type { Metadata } from 'next'
import './globals.css'
import Navbar from '@/components/navbar/Navbar'
import Search from '@/components/searchbar/searchbar'
import { Providers } from './providers'


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({children}: {children: React.ReactNode}) {
  return (
    <html lang="en">

        <link rel="icon" type="image/png" href="/favicon-96x96.png?v=20260331" sizes="96x96" />
        <link rel="icon" type="image/svg+xml" href="/favicon.svg?v=20260331" />
        <link rel="shortcut icon" href="/favicon.ico?v=20260331" />
        <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png?v=20260331" />
        <meta name="apple-mobile-web-app-title" content="MyWebSite" />
        <link rel="manifest" href="/site.webmanifest?v=20260331" />


        {/* <link rel="icon" type="image/png" href="/favicon.ico/favicon-96x96.png?v=20260329" sizes="96x96" />
        <link rel="icon" type="image/svg+xml" href="/favicon.ico/favicon.svg?v=20260329" />
        <link rel="shortcut icon" href="/favicon.ico/favicon.ico?v=20260329" />
        <link rel="apple-touch-icon" sizes="180x180" href="/favicon.ico/apple-touch-icon.png?v=20260329" />
        <meta name="apple-mobile-web-app-title" content="MyWebSite" />
        <link rel="manifest" href="/favicon.ico/site.webmanifest?v=20260329" /> */}
        <body className="">
          <div className="bg-fixed-gradient">
            <div className="bg-layer" />
            <div className="vignette"/>
          </div>
          <Providers>
            <Navbar />
            <Search /> 
            {children}
          </Providers>
        </body>
    </html>
  )
}
