import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import CirlclesBackground from './components/ui/CirclesBackground'
import Navbar from './components/navbar/navbar'
import { AuthProvider } from '../hooks/useAuth'
import CustomProvider from '@/redux/CustomProvider'
import store from '@/redux/store'
import Search from './components/search/searchsection'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({children}: {children: React.ReactNode}) {
  return (
    <html lang="en">
        <body className={`${inter.className}`}>
            <CustomProvider store={store}>
              <AuthProvider>
                <Navbar />
                <Search /> 
                  {/* <CirlclesBackground> */}
                    {children}
                  {/* </CirlclesBackground> */}
              </AuthProvider>
            </CustomProvider>
        </body>
    </html>
  )
}
