import type { Metadata } from 'next'
import './globals.css'
import Navbar from './components/navbar/Navbar'
import Search from './components/search/searchbar'
import { Providers } from './providers'


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({children}: {children: React.ReactNode}) {
  return (
    <html lang="en">
        <body className="">
          <div className="bg-fixed-gradient">
            <div className="bg-layer" />
            <div className="vignette"/>
          </div>
          <Providers>
            <Navbar />
                  <Search /> 
                  {children}
          </Providers>
        </body>
    </html>
  )
}
